####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building a container image from the Dockerfiles shown below, you need to update the default .dockerignore file,
# as it filters everything except the target directory. In order to build inside a container, you need to copy the src
# directory. Thus, edit your .dockerignore and remove the * line.
#
# Build the container image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro-multistage -t stevenjdh/surmiser-app .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 stevenjdh/surmiser-app
#
###

## Stage 1 : build with maven builder image with native capabilities.
FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
RUN ./mvnw package -Pnative

## Stage 2 : create the docker final image.
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --from=build /code/target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
