name: 'build'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
    types: [opened, synchronize, reopened] # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy.
        fetch-depth: 0

    - name: Install AdoptOpenJDK
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11' # Java 11 is better for Quarkus.
        architecture: x64
        impl: hotspot

    - name: Cache SonarCloud Packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven Packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Maven Package # Using JVM mode.
      run: chmod +x ./mvnw && ./mvnw -DskipTests clean package

    - name: Maven Test and SonarCloud
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./mvnw test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey="StevenJDH_quarkus-surmiser-app" \
          -Dsonar.organization="stevenjdh" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login=$SONAR_TOKEN
